import type { AnimationId } from '../animations'
import type { ParamSchema, ParamValues } from './types'

export const PARAM_SCHEMAS: Record<AnimationId, ParamSchema> = {
  cyberspace: [
    {
      key: 'fogDensity',
      label: 'Fog density',
      type: 'range',
      min: 0.01,
      max: 0.08,
      step: 0.001,
      default: 0.028,
    },
    {
      key: 'particleSpeed',
      label: 'Particle speed',
      type: 'range',
      min: 1,
      max: 30,
      step: 0.5,
      default: 14,
    },
    {
      key: 'particleSize',
      label: 'Particle size',
      type: 'range',
      min: 0.1,
      max: 2,
      step: 0.05,
      default: 0.35,
    },
    {
      key: 'particleFlow',
      label: 'Particle flow',
      type: 'range',
      min: 0.5,
      max: 8,
      step: 0.1,
      default: 2.5,
    },
    {
      key: 'diveDistance',
      label: 'Dive distance',
      type: 'range',
      min: 10,
      max: 50,
      step: 1,
      default: 26,
    },
    {
      key: 'fovPunch',
      label: 'FOV punch',
      type: 'range',
      min: 0,
      max: 40,
      step: 1,
      default: 18,
    },
    {
      key: 'pulseInterval',
      label: 'Pulse interval',
      type: 'range',
      min: 0.5,
      max: 6,
      step: 0.1,
      default: 2.6,
    },
    {
      key: 'ambientIntensity',
      label: 'Ambient intensity',
      type: 'range',
      min: 0,
      max: 3,
      step: 0.05,
      default: 1.1,
    },
    {
      key: 'pointLightIntensity',
      label: 'Point light intensity',
      type: 'range',
      min: 10,
      max: 100,
      step: 1,
      default: 50,
    },
    {
      key: 'lightSpeed',
      label: 'Light speed',
      type: 'range',
      min: 2,
      max: 20,
      step: 0.5,
      default: 8,
    },
    {
      key: 'immerseDuration',
      label: 'Enter animation (s)',
      type: 'range',
      min: 0.5,
      max: 4,
      step: 0.1,
      default: 1.4,
    },
  ],
  starship: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'iterations',
      label: 'Iterations',
      type: 'range',
      min: 10,
      max: 80,
      step: 1,
      default: 50,
    },
    {
      key: 'stepSize',
      label: 'Step size',
      type: 'range',
      min: 0.005,
      max: 0.08,
      step: 0.001,
      default: 0.02,
    },
    {
      key: 'accumDiv',
      label: 'Accum divisor',
      type: 'range',
      min: 2000,
      max: 50000,
      step: 500,
      default: 10000,
    },
  ],
  phosphor: [
    {
      key: 'iterations',
      label: 'Iterations',
      type: 'range',
      min: 20,
      max: 120,
      step: 1,
      default: 80,
    },
    {
      key: 'outputScale',
      label: 'Output scale',
      type: 'range',
      min: 2000,
      max: 20000,
      step: 100,
      default: 5000,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  atc: [
    {
      key: 'iterations',
      label: 'Iterations',
      type: 'range',
      min: 10,
      max: 80,
      step: 1,
      default: 50,
    },
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.05,
      max: 1,
      step: 0.01,
      default: 0.2,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'range',
      min: 0.05,
      max: 1,
      step: 0.01,
      default: 0.2,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 0.5,
    },
  ],
  cathedral: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'shader-lines': [
    {
      key: 'timeSpeed',
      label: 'Time speed',
      type: 'range',
      min: 0.01,
      max: 0.2,
      step: 0.005,
      default: 0.05,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'shader-animation': [
    {
      key: 'timeSpeed',
      label: 'Time speed',
      type: 'range',
      min: 0.01,
      max: 0.2,
      step: 0.005,
      default: 0.05,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'anomalous-matter': [
    {
      key: 'rotationSpeed',
      label: 'Rotation speed',
      type: 'range',
      min: 0.0001,
      max: 0.002,
      step: 0.0001,
      default: 0.0005,
    },
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.0001,
      max: 0.001,
      step: 0.00005,
      default: 0.0003,
    },
  ],
  lab: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  launch: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 0.5,
    },
  ],
  'radial-shader': [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  fireflies: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'collective-trajectories': [
    {
      key: 'strandCount',
      label: 'Strand count',
      type: 'range',
      min: 100,
      max: 5000,
      step: 1,
      default: 1000,
    },
    {
      key: 'radius',
      label: 'Radius',
      type: 'range',
      min: 1,
      max: 6,
      step: 0.01,
      default: 3.4,
    },
    {
      key: 'audioReact',
      label: 'Audio → shell',
      type: 'range',
      min: 0,
      max: 4,
      step: 0.01,
      default: 0.8,
    },
    {
      key: 'curl',
      label: 'Curl',
      type: 'range',
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.7,
    },
    {
      key: 'noiseFreq',
      label: 'Noise freq',
      type: 'range',
      min: 0.1,
      max: 3,
      step: 0.01,
      default: 0.85,
    },
    {
      key: 'shimmerSpeed',
      label: 'Shimmer speed',
      type: 'range',
      min: 0,
      max: 0.4,
      step: 0.001,
      default: 0.05,
    },
    {
      key: 'flowSpeed',
      label: 'Flow speed',
      type: 'range',
      min: 0,
      max: 1.5,
      step: 0.01,
      default: 0.2,
    },
    {
      key: 'pulseCount',
      label: 'Pulse count',
      type: 'range',
      min: 0,
      max: 10,
      step: 0.1,
      default: 0.4,
    },
    {
      key: 'endsVsMiddle',
      label: 'Ends vs middle',
      type: 'range',
      min: 0.3,
      max: 5,
      step: 0.01,
      default: 1.8,
    },
    {
      key: 'lineBase',
      label: 'Line base',
      type: 'range',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.45,
    },
    {
      key: 'lineOpacity',
      label: 'Line opacity',
      type: 'range',
      min: 0.05,
      max: 2,
      step: 0.01,
      default: 0.9,
    },
    {
      key: 'extendFraction',
      label: 'Extend fraction',
      type: 'range',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.3,
    },
    {
      key: 'extendReach',
      label: 'Extend reach',
      type: 'range',
      min: 1,
      max: 3,
      step: 0.01,
      default: 2,
    },
    {
      key: 'introGrowTime',
      label: 'Intro grow time',
      type: 'range',
      min: 0.1,
      max: 3,
      step: 0.01,
      default: 0.5,
    },
    {
      key: 'introRandomDelay',
      label: 'Intro random delay',
      type: 'range',
      min: 0,
      max: 15,
      step: 0.01,
      default: 4,
    },
    {
      key: 'glowStrength',
      label: 'Glow strength',
      type: 'range',
      min: 0,
      max: 1.5,
      step: 0.01,
      default: 0.3,
    },
    {
      key: 'glowSize',
      label: 'Glow size',
      type: 'range',
      min: 0,
      max: 0.03,
      step: 0.001,
      default: 0.016,
    },
    {
      key: 'shellDots',
      label: 'Shell dots',
      type: 'range',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.56,
    },
    {
      key: 'shellDotSize',
      label: 'Shell dot size',
      type: 'range',
      min: 0.005,
      max: 0.08,
      step: 0.001,
      default: 0.01,
    },
    {
      key: 'autoRotate',
      label: 'Auto rotate',
      type: 'boolean',
      default: true,
    },
    {
      key: 'coreWireframe',
      label: 'Core wireframe (0=off)',
      type: 'range',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.9,
    },
    {
      key: 'coreRadius',
      label: 'Core radius',
      type: 'range',
      min: 0.05,
      max: 0.8,
      step: 0.005,
      default: 0.22,
    },
    {
      key: 'coreEmanation',
      label: 'Core emanation',
      type: 'range',
      min: 0,
      max: 0.4,
      step: 0.005,
      default: 0.12,
    },
    {
      key: 'coreDetail',
      label: 'Core detail',
      type: 'range',
      min: 0.5,
      max: 6,
      step: 0.05,
      default: 2.6,
    },
    {
      key: 'fogStrength',
      label: 'Fog strength (0=off)',
      type: 'range',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.85,
    },
    {
      key: 'fogNear',
      label: 'Fog near',
      type: 'range',
      min: 0,
      max: 20,
      step: 0.1,
      default: 9,
    },
    {
      key: 'fogFar',
      label: 'Fog far',
      type: 'range',
      min: 1,
      max: 30,
      step: 0.1,
      default: 18,
    },
    {
      key: 'dofDim',
      label: 'DOF dim (0=off)',
      type: 'range',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.6,
    },
    {
      key: 'focusDist',
      label: 'Focus dist',
      type: 'range',
      min: 2,
      max: 20,
      step: 0.05,
      default: 12,
    },
    {
      key: 'focusRange',
      label: 'Focus range',
      type: 'range',
      min: 0.3,
      max: 8,
      step: 0.05,
      default: 3,
    },
    {
      key: 'rippleStrength',
      label: 'Ripple strength (0=off)',
      type: 'range',
      min: 0,
      max: 2,
      step: 0.01,
      default: 1,
    },
    {
      key: 'rippleSpread',
      label: 'Ripple spread (rad)',
      type: 'range',
      min: 0.1,
      max: 1.5,
      step: 0.01,
      default: 0.5,
    },
    {
      key: 'ringSpacing',
      label: 'Ring spacing',
      type: 'range',
      min: 0.02,
      max: 0.4,
      step: 0.005,
      default: 0.12,
    },
    {
      key: 'rippleFade',
      label: 'Ripple fade',
      type: 'range',
      min: 0.2,
      max: 4,
      step: 0.05,
      default: 1.5,
    },
    {
      key: 'audioPlay',
      label: 'Audio play',
      type: 'boolean',
      default: true,
    },
    {
      key: 'audioVolume',
      label: 'Audio volume',
      type: 'range',
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.8,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 0.75,
    },
  ],
  'grid-shader': [
    {
      key: 'timeSpeed',
      label: 'Time speed',
      type: 'range',
      min: 0.001,
      max: 0.05,
      step: 0.001,
      default: 0.01,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
}

export function getDefaultParams(id: AnimationId): ParamValues {
  const schema = PARAM_SCHEMAS[id]
  return Object.fromEntries(schema.map((field) => [field.key, field.default]))
}

export function getParamSchema(id: AnimationId): ParamSchema {
  return PARAM_SCHEMAS[id]
}
