import type { AnimationId } from '../animations'
import type { ParamSchema, ParamValues } from './types'

export const PARAM_SCHEMAS: Record<AnimationId, ParamSchema> = {
  cyberspace: [
    {
      key: 'fogDensity',
      label: 'Fog density',
      type: 'range',
      min: 0.01,
      max: 0.08,
      step: 0.001,
      default: 0.028,
    },
    {
      key: 'particleSpeed',
      label: 'Particle speed',
      type: 'range',
      min: 1,
      max: 30,
      step: 0.5,
      default: 14,
    },
    {
      key: 'particleSize',
      label: 'Particle size',
      type: 'range',
      min: 0.1,
      max: 2,
      step: 0.05,
      default: 0.35,
    },
    {
      key: 'particleFlow',
      label: 'Particle flow',
      type: 'range',
      min: 0.5,
      max: 8,
      step: 0.1,
      default: 2.5,
    },
    {
      key: 'diveDistance',
      label: 'Dive distance',
      type: 'range',
      min: 10,
      max: 50,
      step: 1,
      default: 26,
    },
    {
      key: 'fovPunch',
      label: 'FOV punch',
      type: 'range',
      min: 0,
      max: 40,
      step: 1,
      default: 18,
    },
    {
      key: 'pulseInterval',
      label: 'Pulse interval',
      type: 'range',
      min: 0.5,
      max: 6,
      step: 0.1,
      default: 2.6,
    },
    {
      key: 'ambientIntensity',
      label: 'Ambient intensity',
      type: 'range',
      min: 0,
      max: 3,
      step: 0.05,
      default: 1.1,
    },
    {
      key: 'pointLightIntensity',
      label: 'Point light intensity',
      type: 'range',
      min: 10,
      max: 100,
      step: 1,
      default: 50,
    },
    {
      key: 'lightSpeed',
      label: 'Light speed',
      type: 'range',
      min: 2,
      max: 20,
      step: 0.5,
      default: 8,
    },
    {
      key: 'immerseDuration',
      label: 'Enter animation (s)',
      type: 'range',
      min: 0.5,
      max: 4,
      step: 0.1,
      default: 1.4,
    },
  ],
  starship: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'iterations',
      label: 'Iterations',
      type: 'range',
      min: 10,
      max: 80,
      step: 1,
      default: 50,
    },
    {
      key: 'stepSize',
      label: 'Step size',
      type: 'range',
      min: 0.005,
      max: 0.08,
      step: 0.001,
      default: 0.02,
    },
    {
      key: 'accumDiv',
      label: 'Accum divisor',
      type: 'range',
      min: 2000,
      max: 50000,
      step: 500,
      default: 10000,
    },
  ],
  phosphor: [
    {
      key: 'iterations',
      label: 'Iterations',
      type: 'range',
      min: 20,
      max: 120,
      step: 1,
      default: 80,
    },
    {
      key: 'outputScale',
      label: 'Output scale',
      type: 'range',
      min: 2000,
      max: 20000,
      step: 100,
      default: 5000,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  atc: [
    {
      key: 'iterations',
      label: 'Iterations',
      type: 'range',
      min: 10,
      max: 80,
      step: 1,
      default: 50,
    },
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.05,
      max: 1,
      step: 0.01,
      default: 0.2,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'range',
      min: 0.05,
      max: 1,
      step: 0.01,
      default: 0.2,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 0.5,
    },
  ],
  cathedral: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'shader-lines': [
    {
      key: 'timeSpeed',
      label: 'Time speed',
      type: 'range',
      min: 0.01,
      max: 0.2,
      step: 0.005,
      default: 0.05,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'shader-animation': [
    {
      key: 'timeSpeed',
      label: 'Time speed',
      type: 'range',
      min: 0.01,
      max: 0.2,
      step: 0.005,
      default: 0.05,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'anomalous-matter': [
    {
      key: 'rotationSpeed',
      label: 'Rotation speed',
      type: 'range',
      min: 0.0001,
      max: 0.002,
      step: 0.0001,
      default: 0.0005,
    },
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.0001,
      max: 0.001,
      step: 0.00005,
      default: 0.0003,
    },
  ],
  lab: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  launch: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 0.5,
    },
  ],
  'radial-shader': [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  fireflies: [
    {
      key: 'timeScale',
      label: 'Time scale',
      type: 'range',
      min: 0.1,
      max: 4,
      step: 0.05,
      default: 1,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
  'grid-shader': [
    {
      key: 'timeSpeed',
      label: 'Time speed',
      type: 'range',
      min: 0.001,
      max: 0.05,
      step: 0.001,
      default: 0.01,
    },
    {
      key: 'resolutionScale',
      label: 'Resolution scale',
      type: 'range',
      min: 0.25,
      max: 1,
      step: 0.05,
      default: 1,
    },
  ],
}

export function getDefaultParams(id: AnimationId): ParamValues {
  const schema = PARAM_SCHEMAS[id]
  return Object.fromEntries(schema.map((field) => [field.key, field.default]))
}

export function getParamSchema(id: AnimationId): ParamSchema {
  return PARAM_SCHEMAS[id]
}
